<?xml version="1.0" encoding="utf-8"?><Database Name="PharmedPlastDB" Class="LINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.19.0.15;Initial Catalog=PharmedPlastDB;User ID=t" SettingsObjectName="PharmedPlastPouyan.Properties.Settings" SettingsPropertyName="PharmedPlastDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MachineOrderView" Member="MachineOrderViews">
    <Type Name="MachineOrderView">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayStart" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayFinish" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="see.BalanceView" Member="BalanceViews">
    <Type Name="BalanceView">
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRSalon" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PRControl" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="StoreSalon" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="StoreControl" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DHR" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Sell" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Wastage" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoldWorkOrderView" Member="MoldWorkOrderViews">
    <Type Name="MoldWorkOrderView">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkOrderIDOld" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkOrderIDNew" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineOld" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OldTrail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MachineNew" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewTrail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PROld" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRtmpOld" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRNew" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRtmpNew" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeDate" Type="System.String" DbType="VarChar(92)" CanBeNull="true" />
      <Column Name="ComplateDate" Type="System.String" DbType="VarChar(92)" CanBeNull="true" />
      <Column Name="Request" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_AllPersonal" Member="View_AllPersonals">
    <Type Name="View_AllPersonal">
      <Column Name="PersonalCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonalName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EnglishName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_KPIPR" Member="View_KPIPRs">
    <Type Name="View_KPIPR">
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllPart" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Wastage" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_KPIPRStop" Member="View_KPIPRStops">
    <Type Name="View_KPIPRStop">
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeekNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Kaviteh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveKaviteh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CycleTime" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="StopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StopTime" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ParrentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParrentTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_QCAcceptTable" Member="View_QCAcceptTables">
    <Type Name="View_QCAcceptTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(92)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDNonConf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YearNonConf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeNonConfAccept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Leniency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Correction" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CorrectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Accept" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OP1Condition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OP1Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP2Condition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OP2Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP3Condition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OP3Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_QCtable" Member="View_QCtables">
    <Type Name="View_QCtable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorCodeDiagnosis" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ControlNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SumAssignment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LevelView" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiagnosisLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_tblQCCorrectionView" Member="View_tblQCCorrectionViews">
    <Type Name="View_tblQCCorrectionView">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(92)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorCodeDiagnosis" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ReasonRequestview" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Correction" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PreventionView" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="proceedings" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Review" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.BalanceAll" Member="BalanceAlls">
    <Type Name="BalanceAll">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PRSalon" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PRControl" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="StoreSalon" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="StoreControl" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DHR" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Sell" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Wastage" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Consumed" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WorkOrderYear" Member="WorkOrderYears">
    <Type Name="WorkOrderYear">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PartNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditText" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.Consumed" Member="Consumeds">
    <Type Name="Consumed">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.DHR" Member="DHRs">
    <Type Name="DHR">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.PRControl" Member="PRControls">
    <Type Name="PRControl">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.PRSalon" Member="PRSalons">
    <Type Name="PRSalon">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.Sell" Member="Sells">
    <Type Name="Sell">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.StoreControl" Member="StoreControls">
    <Type Name="StoreControl">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.StoreSalon" Member="StoreSalons">
    <Type Name="StoreSalon">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="balance.Wastage" Member="Wastages">
    <Type Name="Wastage">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Increase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Decrease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AssemblyCompletion" Member="AssemblyCompletions">
    <Type Name="AssemblyCompletion">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDAS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorPR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorCheck" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WastageNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ControlNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AssemblyData" Member="AssemblyDatas">
    <Type Name="AssemblyData">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shift" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeekNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FastCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssemblyNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeTolid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Device1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Device2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Device3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Operator1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Operator2Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Operator2Time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Operator3Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Operator3Time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WastageNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ControlNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Edited" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Request" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastIDEdit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AssemblyDescription" Member="AssemblyDescriptions">
    <Type Name="AssemblyDescription">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDAS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AssemblyFormula" Member="AssemblyFormulas">
    <Type Name="AssemblyFormula">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPRCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PartNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ChartTitle" Member="ChartTitles">
    <Type Name="ChartTitle">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeResult" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tartib" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChartTitleAS" Member="ChartTitleAs">
    <Type Name="ChartTitleA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeResult" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tartib" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChartTitleGR" Member="ChartTitleGRs">
    <Type Name="ChartTitleGR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeResult" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tartib" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GranuleData" Member="GranuleDatas">
    <Type Name="GranuleData">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shift" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeekNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PackageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ICCNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartNum" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="ControlNum" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="WastageNum" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="Kolokhe" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="Formulation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Edited" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Request" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastIDEdit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GranuleDescription" Member="GranuleDescriptions">
    <Type Name="GranuleDescription">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDGranule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GranuleDetail" Member="GranuleDetails">
    <Type Name="GranuleDetail">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDGranule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDBatch" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HeatingMixerNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CoolingMixerNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExtruderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HeatingMixerTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="HeatingMixerTemp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HeatingMixerAmps" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlasticizerTimeFrom" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="PlasticizerTimeTo" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="PlasticizerTempFrom" Type="System.Decimal" DbType="Decimal(4,1) NOT NULL" CanBeNull="false" />
      <Column Name="PlasticizerTempTo" Type="System.Decimal" DbType="Decimal(4,1) NOT NULL" CanBeNull="false" />
      <Column Name="CoolingMixerTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="CoolingMixerTemp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CoolingMixerMaxTemp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="FinishTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GranuleMaterial" Member="GranuleMaterials">
    <Type Name="GranuleMaterial">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDGranule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDBatch" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RawMaterial" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialName" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ICC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartNum" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="SeriSakht" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GranuleStop" Member="GranuleStops">
    <Type Name="GranuleStop">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDGranule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StopTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="See" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MachineSpecs" Member="MachineSpecs">
    <Type Name="MachineSpec">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MachineNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Serial" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Origin" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ManufacturingYear" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="InstallationPosition" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Mold" Member="Molds">
    <Type Name="Mold">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MoldCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MoldNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quetta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDProtection" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalList" Member="PersonalLists">
    <Type Name="PersonalList">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonalName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PersonalCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnglishName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductionData" Member="ProductionDatas">
    <Type Name="ProductionData">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shift" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeekNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FastCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Kaviteh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeOfTolid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeTolid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ControlNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WastageNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WastageStart" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VaznRahgah" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="VaznKoloukheh" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ActiveKaviteh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CycleTime" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="OperatorCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GranuleSeries" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ICCNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Edited" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Request" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastIDEdit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuickSelect" Member="QuickSelects">
    <Type Name="QuickSelect">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Product_Code" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CodeFast" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kind" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Stop" Member="Stops">
    <Type Name="Stop">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDProtection" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StopTime" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="See" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StopDescript" Member="StopDescripts">
    <Type Name="StopDescript">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDStopTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StopDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StopTable" Member="StopTables">
    <Type Name="StopTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParrentStopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Accept" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Reject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FillData" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StopType" Member="StopTypes">
    <Type Name="StopType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StopID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tartib" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParrentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblAdmin" Member="tblAdmins">
    <Type Name="tblAdmin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Parameter" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblAvailability" Member="tblAvailabilities">
    <Type Name="tblAvailability">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDAv" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Analiz" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Tolid" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ghaleb" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Fani" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="QRD" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Anbar" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Sanaye" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblBaseData" Member="tblBaseDatas">
    <Type Name="tblBaseData">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FK_Parent_uid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Tartib" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDescription" Member="tblDescriptions">
    <Type Name="tblDescription">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblRequest" Member="tblRequests">
    <Type Name="tblRequest">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpratorCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="RequestReason" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Accept" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AcceptTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Reject" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TemplateAgend" Member="TemplateAgends">
    <Type Name="TemplateAgend">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkOrderIDOld" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OldTrail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WorkOrderIDNew" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewTrail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Request" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AcceptTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="AcceptOP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserTable" Member="UserTables">
    <Type Name="UserTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PTell" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="IDAv" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="verifyPhone" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnglishName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WorkOrderConfirmation" Member="WorkOrderConfirmations">
    <Type Name="WorkOrderConfirmation">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP1Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP1Condition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OP2Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP2Condition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OP3Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP3Condition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OP4Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP4Condition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WorkOrderMonth" Member="WorkOrderMonths">
    <Type Name="WorkOrderMonth">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayStart" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayFinish" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClosingNotWork" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClosingAll" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CycleTime" Type="System.Decimal" DbType="Decimal(6,3) NOT NULL" CanBeNull="false" />
      <Column Name="ActiveKavite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Aloans" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinPrDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinAllWorkorder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditText" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Confirmation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Mold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WorkOrderTrail" Member="WorkOrderTrails">
    <Type Name="WorkOrderTrail">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayStart" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayFinish" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProdectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TemplateNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Applicant" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditText" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Mold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblQCCorrection" Member="tblQCCorrections">
    <Type Name="tblQCCorrection">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorOrderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorCodeDiagnosis" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ReasonRequest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Correction" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PreventionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="proceedings" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Review" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>